## NumPy array and basics
lear about numpy with chai and code

In [2]:
import numpy as np 

## Creating arry from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array", arr_1d)
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array", arr_2d)


1D array [1 2 3 4 5]
2D array [[1 2 3]
 [4 5 6]
 [7 8 9]]


## List Vs NumPy Array

In [4]:
py_list = [1,2,3]
print("Python list Multiplication",py_list*2)


np_array = np.array([1,2,3]) #Element wise Multiplication
print("Python Array Multiplication",np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range (1000000)]
print("List Operation time :",time.time()-start) 

start = time.time()
np_array = np.arange(1000000)*2
print("List Operation time :",time.time()-start)

Python list Multiplication [1, 2, 3, 1, 2, 3]
Python Array Multiplication [2 4 6]
List Operation time : 0.2693154811859131
List Operation time : 0.012311697006225586


## Creating array from Scratch

In [5]:
zeros = np.zeros((3,4))
print("zeros array:\n",zeros)

ones = np.ones((3,4))
print("zeros array:\n",ones)

full = np.full((3,4), 5)
print("full array:\n",full)

random = np.random.random((2,3))
print("random array:\n",random)

sequence = np.arange(0,10, 2)
print("sequence array:\n",sequence)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
zeros array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
random array:
 [[0.7583958  0.98063277 0.73426646]
 [0.80628376 0.60893343 0.49866839]]
sequence array:
 [0 2 4 6 8]


## Vector,Matrix,Tensor

In [6]:
vector = np.array([1,2,3])
print("vector:", vector)

Matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix:\n",Matrix)

Tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor:\n",Tensor)


vector: [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties


In [7]:
arr = np.array([[1,2,3],[4,5,6]])

print("Shape ",arr.shape)
print("Dimension ",arr.ndim)
print("Size ",arr.size)
print("DType ",arr.dtype)


Shape  (2, 3)
Dimension  2
Size  6
DType  int64


## Array Reshaping


In [13]:
arr = np.arange(12)

print("Original array", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array", reshaped)

flattened = reshaped.flatten()
print("\n Flattned Array", flattened)

#Returns view , Insted of Copy Of original Array
ravled = reshaped.ravel()
print("\n ravled array ", ravled)

Transposr = reshaped.T
print("\nTranspose Array",Transposr)





Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattned Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 ravled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose Array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
